services:
  spark-master:
    image: spark:4.0.1-scala2.13-java21-python3-r-ubuntu
    container_name: spark-master
    ports:
      - "18080:8080"
      - "7077:7077"
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
        --host spark-master
    environment:
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_EVENTLOG_DIR=/opt/spark/logs
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes:
      - ./logs:/opt/spark/logs
      - /home/hp/Bigdata/Data:/data
      - /home/hp/Bigdata/Code:/code
    networks:
      - spark-net

  spark-worker-1:
    image: spark:4.0.1-scala2.13-java21-python3-r-ubuntu
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "18081:8081"
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
        --cores 4
        --memory 3G
        spark://spark-master:7077
    environment:
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./logs:/opt/spark/logs
      - /home/hp/Bigdata/Data:/data
      - /home/hp/Bigdata/Code:/code
    networks:
      - spark-net

  spark-worker-2:
    image: spark:4.0.1-scala2.13-java21-python3-r-ubuntu
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "18082:8081"
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
        --cores 4
        --memory 3G
        spark://spark-master:7077
    environment:
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./logs:/opt/spark/logs
      - /home/hp/Bigdata/Data:/data
      - /home/hp/Bigdata/Code:/code
    networks:
      - spark-net

networks:
  spark-net:
