services:
  db:
    image: postgres:14.20-alpine3.23
    restart: always
    env_file:
      - ../../.env
    environment:
      POSTGRES_DB: ${METABASE_DB_NAME}
      POSTGRES_USER: ${METABASE_DB_USER}
      POSTGRES_PASSWORD: ${METABASE_DB_PASSWORD}
      PGDATA: ${METABASE_DB_DATA_DIR}
    volumes:
      - ./data/postgres:${METABASE_DB_DATA_DIR}
    networks:
      - spark-net

  metabase:
    image: metabase/metabase:v0.57.7.8
    restart: always
    env_file:
      - ../../.env
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_DB_NAME}
      MB_DB_PORT: 5432
      MB_DB_USER: ${METABASE_DB_USER}
      MB_DB_PASS: ${METABASE_DB_PASSWORD}
      MB_DB_HOST: db
      MB_PASSWORD_COMPLEXITY: strong
      MB_PASSWORD_LENGTH: 10
      JAVA_TIMEZONE: ${TZ}
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - db
    networks:
      - spark-net

networks:
  spark-net:
    external: true
