services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    image: spark-custom:3.5.1
    container_name: spark-master
    ports:
      - "18080:8080"
      - "7077:7077"
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
        --host spark-master
    environment:
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes:
      - /home/hp/Bigdata/data:/data:z
      - /home/hp/Bigdata/pipelines:/code:z
    networks:
      - spark-net

  spark-worker:
    image: spark-custom:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "18081:8081"
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
        --cores 4
        --memory 3G
        spark://spark-master:7077
    environment:
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - /home/hp/Bigdata/data:/data:z
      - /home/hp/Bigdata/pipelines:/code:z
    networks:
      - spark-net

networks:
  spark-net:
    external: true
